// ============================================================
// QuestionMaster 全質問定義
// 5カテゴリ × 共通質問セット
// systemWeights: friend / romance / orbiter / cocreation (1..5)
// matchingPattern: similarity / complementary / importance_dependent
// ============================================================

import type { QuestionMaster } from "./types";

export const QUESTION_MASTER: QuestionMaster[] = [
  // ────────────────────────────────────────
  // カテゴリ: tempo (会話・テンポ)
  // ────────────────────────────────────────
  {
    id: "q_tempo_01",
    key: "silence_comfort",
    title: "沈黙の心地よさ",
    prompt: "一緒にいて心地いいのは、静かな時間と、にぎやかな時間、どちらですか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 5, romance: 4, orbiter: 3, cocreation: 3 },
    rigidity: 0.4,
    featureMapping: [
      { featureKey: "calmness", contribution: 0.8 },
      { featureKey: "playfulness", contribution: -0.3 },
    ],
    dailyEligible: true,
    coreEligible: true,
  },
  {
    id: "q_tempo_02",
    key: "conversation_pace",
    title: "会話テンポ",
    prompt: "会話はテンポ良く続く方がよいですか？間があっても自然な方がよいですか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 5, romance: 4, orbiter: 3, cocreation: 4 },
    rigidity: 0.3,
    featureMapping: [
      { featureKey: "pace_match_preference", contribution: 0.9 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_tempo_03",
    key: "depth_vs_light",
    title: "会話の深さ",
    prompt: "深い話をしたいですか？軽い話を心地よく続けたいですか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 3, romance: 4, orbiter: 4, cocreation: 4 },
    rigidity: 0.35,
    featureMapping: [
      { featureKey: "depth", contribution: 0.9 },
      { featureKey: "playfulness", contribution: -0.4 },
    ],
    dailyEligible: true,
    coreEligible: true,
  },
  {
    id: "q_tempo_04",
    key: "response_speed",
    title: "返信スピード",
    prompt: "メッセージの返信は早い方が安心しますか？ゆっくりでも気にならないですか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 4, orbiter: 3, cocreation: 3 },
    rigidity: 0.25,
    featureMapping: [
      { featureKey: "pace_match_preference", contribution: 0.5 },
      { featureKey: "attachment_style_preference", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_tempo_05",
    key: "energy_in_group",
    title: "集団での立ち位置",
    prompt: "グループでは話を回す方ですか？聞き手に回る方ですか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "complementary",
    systemWeights: { friend: 4, romance: 2, orbiter: 2, cocreation: 4 },
    rigidity: 0.3,
    featureMapping: [
      { featureKey: "playfulness", contribution: 0.5 },
      { featureKey: "independence", contribution: -0.2 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_tempo_06",
    key: "humor_style",
    title: "ユーモアの温度",
    prompt: "一緒に笑い合える相手と、静かに共感し合える相手、どちらにより惹かれますか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 4, romance: 3, orbiter: 2, cocreation: 3 },
    rigidity: 0.2,
    featureMapping: [
      { featureKey: "playfulness", contribution: 0.7 },
      { featureKey: "calmness", contribution: -0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_tempo_07",
    key: "listening_style",
    title: "聴き方の好み",
    prompt: "話を聞いてもらうとき、アドバイスがほしいですか？ただ聞いてほしいですか？",
    category: "tempo",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 5, orbiter: 4, cocreation: 3 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "emotional_openness", contribution: 0.6 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },

  // ────────────────────────────────────────
  // カテゴリ: distance (距離感)
  // ────────────────────────────────────────
  {
    id: "q_dist_01",
    key: "closeness_speed",
    title: "距離の縮まり方",
    prompt: "すぐ近づく関係がよいですか？ゆっくり距離が縮む方がよいですか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 5, orbiter: 4, cocreation: 2 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "intimacy_pacing", contribution: 0.9 },
      { featureKey: "attachment_style_preference", contribution: 0.4 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_dist_02",
    key: "contact_frequency",
    title: "連絡頻度",
    prompt: "連絡頻度は多い方が安心しますか？少なくても平気ですか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 4, romance: 5, orbiter: 4, cocreation: 3 },
    rigidity: 0.4,
    featureMapping: [
      { featureKey: "attachment_style_preference", contribution: 0.7 },
      { featureKey: "independence", contribution: -0.4 },
    ],
    dailyEligible: true,
    coreEligible: true,
  },
  {
    id: "q_dist_03",
    key: "emotional_sharing",
    title: "感情の共有タイミング",
    prompt: "感情や不安はすぐ共有したいですか？自分で整理してから話したいですか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 5, orbiter: 5, cocreation: 3 },
    rigidity: 0.6,
    featureMapping: [
      { featureKey: "emotional_openness", contribution: 0.9 },
      { featureKey: "independence", contribution: -0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_dist_04",
    key: "alone_time_need",
    title: "一人の時間",
    prompt: "一人の時間はどれくらい必要ですか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 4, orbiter: 5, cocreation: 2 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "independence", contribution: 0.8 },
      { featureKey: "calmness", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_dist_05",
    key: "dependency_comfort",
    title: "頼り合いの心地よさ",
    prompt: "相手に頼られるのは嬉しいですか？負担に感じやすいですか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "complementary",
    systemWeights: { friend: 2, romance: 4, orbiter: 5, cocreation: 3 },
    rigidity: 0.4,
    featureMapping: [
      { featureKey: "attachment_style_preference", contribution: 0.6 },
      { featureKey: "independence", contribution: -0.5 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_dist_06",
    key: "jealousy_tolerance",
    title: "嫉妬と安心",
    prompt: "相手が他の人と親しくしていても平気ですか？少し気になりますか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 1, romance: 5, orbiter: 4, cocreation: 1 },
    rigidity: 0.6,
    featureMapping: [
      { featureKey: "attachment_style_preference", contribution: 0.7 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_dist_07",
    key: "physical_affection",
    title: "身体的な距離感",
    prompt: "スキンシップは自然に増える方がよいですか？慎重に始めたいですか？",
    category: "distance",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 1, romance: 5, orbiter: 3, cocreation: 1 },
    rigidity: 0.7,
    featureMapping: [
      { featureKey: "intimacy_pacing", contribution: 0.8 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },

  // ────────────────────────────────────────
  // カテゴリ: values (価値観)
  // ────────────────────────────────────────
  {
    id: "q_val_01",
    key: "stability_vs_stimulation",
    title: "安定 vs 刺激",
    prompt: "安定を重視しますか？刺激を重視しますか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 3, romance: 4, orbiter: 5, cocreation: 4 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "long_term_stability", contribution: 0.8 },
      { featureKey: "novelty", contribution: -0.7 },
    ],
    dailyEligible: true,
    coreEligible: true,
  },
  {
    id: "q_val_02",
    key: "planning_style",
    title: "計画性",
    prompt: "計画を立てたいですか？流れに任せたいですか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "complementary",
    systemWeights: { friend: 2, romance: 3, orbiter: 4, cocreation: 5 },
    rigidity: 0.3,
    featureMapping: [
      { featureKey: "lifestyle_regularity", contribution: 0.6 },
      { featureKey: "novelty", contribution: -0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_val_03",
    key: "freedom_vs_security",
    title: "自由と安定",
    prompt: "将来を考える上で、自由と安定のどちらが大事ですか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 4, orbiter: 5, cocreation: 4 },
    rigidity: 0.6,
    featureMapping: [
      { featureKey: "long_term_stability", contribution: 0.7 },
      { featureKey: "independence", contribution: 0.5 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_val_04",
    key: "growth_orientation",
    title: "成長志向",
    prompt: "自分を変えていきたいですか？今の自分を大切にしたいですか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 3, romance: 3, orbiter: 3, cocreation: 5 },
    rigidity: 0.2,
    featureMapping: [
      { featureKey: "novelty", contribution: 0.6 },
      { featureKey: "long_term_stability", contribution: -0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_val_05",
    key: "tradition_vs_new",
    title: "伝統と新しさ",
    prompt: "慣れたやり方を大事にしますか？新しいやり方を試したいですか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 2, orbiter: 4, cocreation: 4 },
    rigidity: 0.3,
    featureMapping: [
      { featureKey: "novelty", contribution: 0.7 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_val_06",
    key: "empathy_vs_logic",
    title: "共感と論理",
    prompt: "大事な判断をするとき、感情を重視しますか？論理を重視しますか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 3, romance: 4, orbiter: 4, cocreation: 4 },
    rigidity: 0.4,
    featureMapping: [
      { featureKey: "emotional_openness", contribution: 0.5 },
      { featureKey: "value_alignment", contribution: 0.4 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_val_07",
    key: "honesty_directness",
    title: "率直さ",
    prompt: "思ったことは率直に伝えたいですか？相手に合わせて調整しますか？",
    category: "values",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 4, romance: 4, orbiter: 4, cocreation: 5 },
    rigidity: 0.45,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.4 },
      { featureKey: "emotional_openness", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },

  // ────────────────────────────────────────
  // カテゴリ: lifestyle (生活)
  // ────────────────────────────────────────
  {
    id: "q_life_01",
    key: "weekend_style",
    title: "休日の過ごし方",
    prompt: "休日は静かに過ごしたいですか？外に出たいですか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 4, romance: 3, orbiter: 4, cocreation: 3 },
    rigidity: 0.2,
    featureMapping: [
      { featureKey: "calmness", contribution: 0.5 },
      { featureKey: "novelty", contribution: 0.4 },
    ],
    dailyEligible: true,
    coreEligible: true,
  },
  {
    id: "q_life_02",
    key: "rhythm_match",
    title: "生活リズム",
    prompt: "生活リズムが近い方がよいですか？違ってもよいですか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 3, orbiter: 5, cocreation: 4 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "lifestyle_regularity", contribution: 0.8 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_life_03",
    key: "money_sense",
    title: "金銭感覚",
    prompt: "金銭感覚の近さをどれくらい重視しますか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 3, orbiter: 5, cocreation: 4 },
    rigidity: 0.7,
    featureMapping: [
      { featureKey: "value_alignment", contribution: 0.5 },
      { featureKey: "long_term_stability", contribution: 0.4 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_life_04",
    key: "tidiness",
    title: "整理整頓",
    prompt: "部屋はきれいに保ちたいですか？多少散らかっていても気にならないですか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 1, romance: 3, orbiter: 5, cocreation: 3 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "lifestyle_regularity", contribution: 0.6 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_life_05",
    key: "social_circle",
    title: "交友関係の広さ",
    prompt: "友達は広く浅い方ですか？狭く深い方ですか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 5, romance: 2, orbiter: 2, cocreation: 3 },
    rigidity: 0.2,
    featureMapping: [
      { featureKey: "depth", contribution: 0.4 },
      { featureKey: "independence", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_life_06",
    key: "health_consciousness",
    title: "健康意識",
    prompt: "健康や体調管理をどれくらい意識していますか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 1, romance: 2, orbiter: 4, cocreation: 3 },
    rigidity: 0.3,
    featureMapping: [
      { featureKey: "lifestyle_regularity", contribution: 0.4 },
      { featureKey: "long_term_stability", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_life_07",
    key: "work_life_balance",
    title: "仕事とプライベート",
    prompt: "仕事に全力を注ぎたいですか？プライベートを大切にしたいですか？",
    category: "lifestyle",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 3, orbiter: 5, cocreation: 4 },
    rigidity: 0.4,
    featureMapping: [
      { featureKey: "long_term_stability", contribution: 0.4 },
      { featureKey: "independence", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },

  // ────────────────────────────────────────
  // カテゴリ: conflict (衝突と修復)
  // ────────────────────────────────────────
  {
    id: "q_conf_01",
    key: "conflict_timing",
    title: "衝突時のタイミング",
    prompt: "違いがあった時、すぐ話したいですか？少し時間を置きたいですか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 4, orbiter: 5, cocreation: 5 },
    rigidity: 0.6,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.8 },
      { featureKey: "emotional_openness", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_conf_02",
    key: "feedback_style",
    title: "伝え方の好み",
    prompt: "相手にはっきり言ってほしいですか？やわらかく伝えてほしいですか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 5, orbiter: 5, cocreation: 5 },
    rigidity: 0.55,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.5 },
      { featureKey: "emotional_openness", contribution: 0.4 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_conf_03",
    key: "conflict_priority",
    title: "衝突 vs 修復",
    prompt: "関係で大切なのは、衝突しないことですか？衝突後に修復できることですか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 3, romance: 4, orbiter: 5, cocreation: 5 },
    rigidity: 0.7,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.9 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_conf_04",
    key: "apology_style",
    title: "謝り方",
    prompt: "自分が悪い時、すぐ謝れますか？認めるまでに時間がかかりますか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 4, orbiter: 5, cocreation: 4 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.7 },
      { featureKey: "emotional_openness", contribution: 0.2 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_conf_05",
    key: "compromise_willingness",
    title: "妥協と譲歩",
    prompt: "意見が合わない時、妥協点を探しますか？自分の意見を通したいですか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "complementary",
    systemWeights: { friend: 3, romance: 4, orbiter: 5, cocreation: 5 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.6 },
      { featureKey: "independence", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_conf_06",
    key: "forgiveness_speed",
    title: "許し方",
    prompt: "一度怒っても切り替えは早い方ですか？引きずりやすい方ですか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "similarity",
    systemWeights: { friend: 2, romance: 4, orbiter: 5, cocreation: 4 },
    rigidity: 0.5,
    featureMapping: [
      { featureKey: "conflict_repair_orientation", contribution: 0.5 },
      { featureKey: "emotional_openness", contribution: 0.3 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
  {
    id: "q_conf_07",
    key: "boundary_clarity",
    title: "境界線の明確さ",
    prompt: "嫌なことは嫌とはっきり言える方ですか？我慢してしまう方ですか？",
    category: "conflict",
    answerType: "scale",
    scaleMin: 1,
    scaleMax: 5,
    matchingPattern: "importance_dependent",
    systemWeights: { friend: 3, romance: 4, orbiter: 4, cocreation: 5 },
    rigidity: 0.4,
    featureMapping: [
      { featureKey: "independence", contribution: 0.5 },
      { featureKey: "conflict_repair_orientation", contribution: 0.4 },
    ],
    dailyEligible: false,
    coreEligible: true,
  },
];

/** 質問IDで引く用のMap */
export const QUESTION_MAP = new Map(
  QUESTION_MASTER.map((q) => [q.id, q]),
);

/** 初回コア質問のみ */
export const CORE_QUESTIONS = QUESTION_MASTER.filter((q) => q.coreEligible);

/** 毎日質問対象のみ */
export const DAILY_ELIGIBLE_QUESTIONS = QUESTION_MASTER.filter(
  (q) => q.dailyEligible,
);

/** カテゴリ別にグループ化 */
export function groupByCategory() {
  const groups = new Map<string, QuestionMaster[]>();
  for (const q of QUESTION_MASTER) {
    const list = groups.get(q.category) ?? [];
    list.push(q);
    groups.set(q.category, list);
  }
  return groups;
}
