"use client";

import Link from "next/link";
import { motion } from "framer-motion";

interface GrowthItem {
  key: string;
  icon: string;
  label: string;
  progress: number;        // 0-100
  source: string;          // e.g. "Stargazer"
  nextMilestone?: string;  // e.g. "あと27問で深層解析"
  href: string;
  isAutoGenerated?: boolean; // Presence等、自動生成の場合
  isOneTime?: boolean;      // Phenotype等、1回完了の場合
  benefit: string;          // ユーザーメリット
}

interface Props {
  items?: GrowthItem[];
  genomeCompleteness?: number;
}

export default function GrowthMap({ items, genomeCompleteness = 0 }: Props) {
  const defaultItems: GrowthItem[] = [
    {
      key: "stargazer",
      icon: "✦",
      label: "Stargazer",
      progress: 0,
      source: "観測",
      nextMilestone: "観測を始めましょう",
      href: "/stargazer",
      benefit: "判断原理と内面の矛盾がわかる",
    },
    {
      key: "phenotype",
      icon: "🧬",
      label: "Phenotype",
      progress: 0,
      source: "身体分析",
      nextMilestone: "分析を開始しましょう",
      href: "/body-color/avatar",
      isOneTime: true,
      benefit: "パーソナルカラーと身体特性がGenomeに載る",
    },
    {
      key: "origin",
      icon: "🌍",
      label: "Origin",
      progress: 0,
      source: "ルーツ",
      nextMilestone: "記録を始めましょう",
      href: "/origin",
      benefit: "生活圏と行動パターンが可視化される",
    },
    {
      key: "style",
      icon: "◆",
      label: "Style",
      progress: 0,
      source: "好み",
      nextMilestone: "クイズ未回答",
      href: "/my-style?source=aneurasync&mode=sync",
      benefit: "スタイルDNAがGenomeに反映される",
    },
    {
      key: "presence",
      icon: "🪞",
      label: "Presence",
      progress: 0,
      source: "自動生成",
      href: "/sns/profile",
      isAutoGenerated: true,
      benefit: "観測データから自動で構築中",
    },
  ];

  const growthItems = items ?? defaultItems;

  return (
    <section className="px-4 space-y-3">
      <h2 className="text-sm font-bold" style={{ color: "#1a1a2e" }}>
        あなたの観測マップ
      </h2>

      <div
        style={{
          borderRadius: 18,
          background: "linear-gradient(145deg, #ffffff 0%, #f5f6fa 100%)",
          border: "1px solid rgba(0,0,0,0.06)",
          boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
          padding: 16,
        }}
      >
        <div className="space-y-3">
          {growthItems.map((item, i) => (
            <motion.div
              key={item.key}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.06, duration: 0.18 }}
            >
              <Link
                href={item.href}
                className="flex items-center gap-3 group"
                style={{ textDecoration: "none", color: "inherit" }}
              >
                <span className="text-base flex-shrink-0">{item.icon}</span>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-medium" style={{ color: "#1a1a2e" }}>
                      {item.label}
                    </span>
                    {item.isAutoGenerated ? (
                      <span className="text-[10px]" style={{ color: "#8888a0" }}>自動生成</span>
                    ) : item.isOneTime && item.progress >= 100 ? (
                      <span className="text-[10px] font-medium" style={{ color: "#10B981" }}>✓ 完了</span>
                    ) : (
                      <span className="text-[10px] font-medium" style={{ color: "#8B5CF6" }}>
                        {item.progress}%
                      </span>
                    )}
                  </div>
                  {/* プログレスバー */}
                  <div className="w-full h-1.5 rounded-full overflow-hidden" style={{ background: "rgba(0,0,0,0.06)" }}>
                    <motion.div
                      className="h-full rounded-full"
                      style={{
                        background: item.isAutoGenerated
                          ? "linear-gradient(90deg, #94A3B8, #CBD5E1)"
                          : "linear-gradient(90deg, #8B5CF6, #EC4899)",
                      }}
                      initial={{ width: 0 }}
                      animate={{ width: `${Math.max(item.progress, 2)}%` }}
                      transition={{ duration: 0.25, delay: i * 0.06 }}
                    />
                  </div>
                  {item.nextMilestone && !item.isAutoGenerated && (
                    <p className="text-[10px] mt-0.5" style={{ color: "#8888a0" }}>
                      → {item.nextMilestone}
                    </p>
                  )}
                  {item.isAutoGenerated && (
                    <p className="text-[10px] mt-0.5" style={{ color: "#8888a0" }}>
                      → {item.benefit}
                    </p>
                  )}
                </div>
                <span className="text-slate-300 group-hover:text-slate-500 transition-colors text-xs">›</span>
              </Link>
            </motion.div>
          ))}
        </div>

        {/* Genome 完成度 */}
        <div className="mt-4 pt-3" style={{ borderTop: "1px solid rgba(0,0,0,0.06)" }}>
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-xs font-medium" style={{ color: "#1a1a2e" }}>
              Genome 完成度
            </span>
            <span className="text-xs font-bold" style={{ color: "#8B5CF6" }}>
              {genomeCompleteness}%
            </span>
          </div>
          <div className="w-full h-2 rounded-full overflow-hidden" style={{ background: "rgba(0,0,0,0.06)" }}>
            <motion.div
              className="h-full rounded-full"
              style={{ background: "linear-gradient(90deg, #8B5CF6, #EC4899, #F59E0B)" }}
              initial={{ width: 0 }}
              animate={{ width: `${Math.max(genomeCompleteness, 2)}%` }}
              transition={{ duration: 0.8 }}
            />
          </div>
          <p className="text-[10px] mt-1" style={{ color: "#8888a0" }}>
            完成するとRendezvousでの出会いがもっと深くなるよ
          </p>
        </div>
      </div>
    </section>
  );
}
