"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import JourneyMap from "./JourneyMap";
import { AXIS_LABELS } from "@/lib/stargazer/axisLabels";

const mono = "'JetBrains Mono','SF Mono',monospace";

const AXIS_DISPLAY: { key: string; label: string; angle: number }[] = [
  { key: "cautious_vs_bold", label: "慎重⇔大胆", angle: -Math.PI / 2 },
  { key: "analytical_vs_intuitive", label: "分析⇔直感", angle: -Math.PI / 2 + (2 * Math.PI / 8) },
  { key: "introvert_vs_extrovert", label: "内向⇔外向", angle: -Math.PI / 2 + (4 * Math.PI / 8) },
  { key: "plan_vs_spontaneous", label: "計画⇔即興", angle: -Math.PI / 2 + (6 * Math.PI / 8) },
  { key: "individual_vs_social", label: "個人⇔社会", angle: -Math.PI / 2 + (8 * Math.PI / 8) },
  { key: "independence_vs_harmony", label: "自律⇔協調", angle: -Math.PI / 2 + (10 * Math.PI / 8) },
  { key: "function_vs_expression", label: "機能⇔表現", angle: -Math.PI / 2 + (12 * Math.PI / 8) },
  { key: "minimal_vs_maximal", label: "少⇔多", angle: -Math.PI / 2 + (14 * Math.PI / 8) },
];

function StargazerRadar({ axes }: { axes: Record<string, number> }) {
  const cx = 80, cy = 80, r = 60;
  const active = AXIS_DISPLAY.filter(a => Math.abs(axes[a.key] ?? 0) > 0.01);
  if (active.length === 0) return null;

  // Recalculate angles for active axes only
  const items = active.map((a, i) => ({
    ...a,
    angle: -Math.PI / 2 + (2 * Math.PI / active.length) * i,
    value: (axes[a.key] + 1) / 2, // -1..1 → 0..1
  }));

  const pts = items.map(({ angle, value }) => {
    const v = value * r;
    return `${cx + v * Math.cos(angle)},${cy + v * Math.sin(angle)}`;
  }).join(" ");

  return (
    <svg viewBox="0 0 160 160" style={{ width: "100%", maxWidth: 110, margin: "0 auto", display: "block" }}>
      {/* Grid */}
      {[0.33, 0.66, 1.0].map(lv => (
        <polygon key={lv}
          points={items.map(({ angle }) => `${cx + r * lv * Math.cos(angle)},${cy + r * lv * Math.sin(angle)}`).join(" ")}
          fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="0.5" />
      ))}
      {/* Axes */}
      {items.map(({ key, angle }) => (
        <line key={key} x1={cx} y1={cy} x2={cx + r * Math.cos(angle)} y2={cy + r * Math.sin(angle)}
          stroke="rgba(255,255,255,0.08)" strokeWidth="0.5" />
      ))}
      {/* Center line */}
      {items.map(({ key, angle }) => (
        <circle key={`c-${key}`} cx={cx + r * 0.5 * Math.cos(angle)} cy={cy + r * 0.5 * Math.sin(angle)} r="1" fill="rgba(255,255,255,0.1)" />
      ))}
      {/* Data polygon */}
      <polygon points={pts} fill="rgba(139,92,246,0.2)" stroke="rgba(139,92,246,0.8)" strokeWidth="1.5" />
      {/* Data points */}
      {items.map(({ key, angle, value }) => (
        <circle key={`p-${key}`} cx={cx + value * r * Math.cos(angle)} cy={cy + value * r * Math.sin(angle)} r="2.5" fill="rgba(139,92,246,0.9)" />
      ))}
      {/* Labels */}
      {items.map(({ key, label, angle }) => {
        const lx = cx + (r + 16) * Math.cos(angle);
        const ly = cy + (r + 16) * Math.sin(angle);
        return (
          <text key={`l-${key}`} x={lx} y={ly} textAnchor="middle" dominantBaseline="middle"
            fill="rgba(255,255,255,0.45)" fontSize="7" fontFamily={mono}>
            {label}
          </text>
        );
      })}
    </svg>
  );
}

type IdentityElement = {
  key: string;
  label: string;
  emoji: string;
  color: string;
  pct: number;
  insight: string;
  href: string;
  isAutoGenerated?: boolean;
};

type Props = {
  sgData: {
    archetype?: string | null;
    emoji?: string | null;
    confidence?: number;
    observationCount?: number;
    figureSrc?: string | null;
    axisScores?: Record<string, number>;
  } | null;
  identityLive: Partial<Record<string, { pct: number; insight: string }>>;
  ptData: { pct: number; insight: string } | null;
  identityElements: IdentityElement[];
  genomeCompleteness: number;
  journeyMapProps: {
    identityLive: any;
    phenotypePct: number;
    stargazerConfidence: number;
    observationCount: number;
  };
};

export default function YourSelfSection({
  sgData,
  identityLive,
  ptData,
  identityElements,
  genomeCompleteness,
  journeyMapProps,
}: Props) {
  const [expanded, setExpanded] = useState(false);
  const displayElements = expanded ? identityElements : identityElements.slice(0, 4);

  // Fetch genome card data for rich display
  const [gcData, setGcData] = useState<{
    coreValue?: string | null;
    dilemma?: string | null;
    currentCuriosity?: string | null;
    lastObservedAt?: string | null;
    pcSeason?: string | null;
    topTraits?: { label: string; score: number }[] | null;
    topStyleLanes?: string[] | null;
    radarAxes?: { analytical: number; cautious: number; social: number; expressive: number; independent: number } | null;
  } | null>(null);

  useEffect(() => {
    fetch("/api/genome-card", { credentials: "include" })
      .then((r) => r.ok ? r.json() : null)
      .then((d) => {
        if (!d?.ok || !d.card) return;
        const c = d.card;
        setGcData({
          coreValue: c.cardFront?.coreValue ?? null,
          dilemma: c.cardFront?.dilemma ?? null,
          currentCuriosity: c.cardFront?.currentCuriosity ?? null,
          lastObservedAt: c.cardFront?.lastObservedAt ?? null,
          pcSeason: c.pcSeason ?? null,
          topTraits: c.topTraits ?? null,
          topStyleLanes: c.topStyleLanes ?? null,
          radarAxes: c.cardBack?.radarAxes ?? null,
        });
      })
      .catch((err) => {
        console.warn("[YourSelfSection] genome-card fetch failed:", err?.message);
        setGcData(null);
      });
  }, []);

  return (
    <section
      aria-label="あなた自身"
      style={{
        padding: "32px 20px 24px",
        maxWidth: 780,
        margin: "0 auto",
        position: "relative",
      }}
    >
      {/* Section header */}
      <div style={{ textAlign: "center", marginBottom: 20 }}>
        <span
          style={{
            fontSize: 11,
            color: "#6b6b80",
            letterSpacing: 5,
            fontWeight: 600,
            fontFamily: mono,
          }}
        >
          あなた自身
        </span>
        <div
          style={{ fontSize: 14, color: "#1a1a2e", marginTop: 4, fontWeight: 700 }}
        >
          わかってきた、あなたのこと
        </div>
      </div>

      {/* Genome Card (living card) → /aneurasync/genome — Dark premium design */}
      <Link
        href="/aneurasync/genome"
        style={{
          display: "block",
          marginBottom: 14,
          padding: "20px 20px 18px",
          borderRadius: 22,
          background: "linear-gradient(155deg, rgba(28,20,48,0.94) 0%, rgba(42,28,75,0.92) 40%, rgba(30,22,55,0.95) 100%)",
          border: "1.5px solid rgba(168,85,247,0.3)",
          boxShadow: "0 12px 40px rgba(28,12,55,0.35), 0 4px 12px rgba(0,0,0,0.15), 0 0 0 1px rgba(139,92,246,0.05), inset 0 1px 0 rgba(255,255,255,0.06)",
          textDecoration: "none",
          color: "#fff",
          position: "relative",
          overflow: "hidden",
        }}
      >
        {/* Ambient glow */}
        <div style={{ position: "absolute", top: -40, right: -30, width: 160, height: 160, borderRadius: "50%", background: "radial-gradient(circle, rgba(139,92,246,0.15), transparent 70%)", pointerEvents: "none" }} />

        {/* Top: Header + Figure */}
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", position: "relative", zIndex: 1 }}>
          {/* Left: Type info */}
          <div style={{ flex: 1 }}>
            {/* あなたのジーン label */}
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
              <div style={{ width: 32, height: 32, borderRadius: 10, background: "rgba(139,92,246,0.2)", border: "1px solid rgba(139,92,246,0.3)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>
                {sgData?.emoji ?? "✦"}
              </div>
              <div>
                <div style={{ fontSize: 8, color: "rgba(255,255,255,0.4)", letterSpacing: 2, fontFamily: mono }}>あなたのジーン</div>
                <div style={{ fontSize: 10, color: "rgba(255,255,255,0.6)" }}>Genome Card</div>
              </div>
            </div>

            {/* Archetype name — large */}
            <div style={{ fontSize: 22, fontWeight: 900, letterSpacing: -0.5, marginBottom: 12, textShadow: "0 2px 12px rgba(0,0,0,0.3)" }}>
              {sgData?.archetype ?? "分析中..."}
            </div>

            {/* Card content */}
            <div style={{ display: "flex", flexDirection: "column", gap: 6, fontSize: 11, lineHeight: 1.5 }}>
              <div style={{ display: "flex", alignItems: "flex-start", gap: 6 }}>
                <span style={{ flexShrink: 0 }}>🔑</span>
                <span style={{ color: "rgba(255,255,255,0.75)", fontWeight: 500 }}>
                  {gcData?.coreValue ?? ((sgData?.observationCount ?? 0) >= 10 ? "あなたが大事にしてることを分析中..." : "3問答えるだけで、自分でも気づいてなかった大事なことが見えるよ")}
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "flex-start", gap: 6 }}>
                <span style={{ flexShrink: 0 }}>🌀</span>
                <span style={{ color: "rgba(255,255,255,0.65)", fontWeight: 500 }}>
                  {gcData?.dilemma ?? ((sgData?.observationCount ?? 0) >= 20 ? "あなたの中で揺れてるものを分析中..." : "自分でも気づいてない「迷い」がここに出てくるよ")}
                </span>
              </div>
              {gcData?.currentCuriosity && (
                <div style={{ display: "flex", alignItems: "flex-start", gap: 6 }}>
                  <span style={{ flexShrink: 0 }}>💭</span>
                  <span style={{ color: "rgba(139,176,246,0.9)", fontWeight: 500 }}>{gcData.currentCuriosity}</span>
                </div>
              )}
            </div>

            {/* Trait badges */}
            <div style={{ display: "flex", flexWrap: "wrap", gap: 5, marginTop: 10 }}>
              {gcData?.pcSeason && (
                <span style={{ fontSize: 9, padding: "3px 8px", borderRadius: 8, background: "rgba(236,72,153,0.15)", border: "1px solid rgba(236,72,153,0.25)", color: "#f472b6", fontWeight: 600 }}>
                  🎨 {gcData.pcSeason}
                </span>
              )}
              {gcData?.topTraits?.slice(0, 2).map((t, i) => (
                <span key={i} style={{ fontSize: 9, padding: "3px 8px", borderRadius: 8, background: "rgba(139,92,246,0.15)", border: "1px solid rgba(139,92,246,0.25)", color: "#a78bfa", fontWeight: 600 }}>
                  {t.label} {t.score}%
                </span>
              ))}
            </div>
          </div>

          {/* Right: Character figure */}
          {sgData?.figureSrc && (
            <div style={{
              width: 120, height: 140, borderRadius: 16, overflow: "hidden", flexShrink: 0, marginLeft: 12,
              position: "relative",
              filter: "drop-shadow(0 8px 20px rgba(0,0,0,0.4))",
            }}>
              <img src={sgData.figureSrc} alt={sgData?.archetype ?? ""} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
            </div>
          )}
        </div>

        {/* Stargazer Radar Chart (compact, inline) */}
        {sgData?.axisScores && Object.keys(sgData.axisScores).length > 0 && (
          <div style={{ marginTop: 12, padding: "10px 14px", borderRadius: 14, background: "rgba(139,92,246,0.08)", border: "1px solid rgba(139,92,246,0.15)", position: "relative", zIndex: 1, display: "flex", alignItems: "center", gap: 14 }}>
            <div style={{ width: 110, flexShrink: 0 }}>
              <StargazerRadar axes={sgData.axisScores} />
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 8, color: "rgba(255,255,255,0.4)", letterSpacing: 2, fontFamily: mono, marginBottom: 6 }}>軸</div>
              {(() => {
                const sorted = Object.entries(sgData.axisScores)
                  .filter(([, v]) => Math.abs(v) > 0.1)
                  .sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]))
                  .slice(0, 3);
                return sorted.map(([key, val]) => {
                  const label = AXIS_LABELS[key] ?? AXIS_DISPLAY.find(a => a.key === key)?.label ?? key.replace(/_/g, " ");
                  return (
                    <div key={key} style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 3 }}>
                      <div style={{ width: 40, height: 3, borderRadius: 2, background: "rgba(255,255,255,0.08)", overflow: "hidden", position: "relative" }}>
                        <div style={{ position: "absolute", top: 0, height: "100%", borderRadius: 2, left: val >= 0 ? "50%" : `${((val + 1) / 2) * 100}%`, width: `${Math.abs(val) * 50}%`, background: "linear-gradient(90deg, #a78bfa, #6366F1)" }} />
                      </div>
                      <span style={{ fontSize: 8, color: "rgba(255,255,255,0.5)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 80 }}>{label}</span>
                    </div>
                  );
                });
              })()}
            </div>
          </div>
        )}

        {/* Bottom: Freshness + CTA */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 14, position: "relative", zIndex: 1 }}>
          {gcData?.lastObservedAt ? (
            <div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", fontFamily: mono, display: "flex", alignItems: "center", gap: 4 }}>
              <span style={{ width: 5, height: 5, borderRadius: "50%", background: "#22c55e", animation: "gcPulse 2s ease-in-out infinite" }} />
              最終観測: {(() => { const h = Math.floor((Date.now() - new Date(gcData.lastObservedAt!).getTime()) / 3600000); return h < 1 ? "たった今" : h < 24 ? `${h}時間前` : `${Math.floor(h / 24)}日前`; })()}
            </div>
          ) : <div />}
          <div style={{
            padding: "7px 16px", borderRadius: 12,
            background: "linear-gradient(135deg, rgba(139,92,246,0.2), rgba(99,102,241,0.15))",
            border: "1px solid rgba(139,92,246,0.3)",
            fontSize: 11, fontWeight: 700, color: "#fff",
            display: "flex", alignItems: "center", gap: 6,
          }}>
            もっと詳しく見る →
          </div>
        </div>

        <style>{`@keyframes gcPulse { 0%,100% { opacity:1;transform:scale(1) } 50% { opacity:0.4;transform:scale(1.4) } }`}</style>
      </Link>

      {/* Presence (auto-generated) */}
      <Link
        href="/sns/profile"
        style={{
          display: "flex",
          alignItems: "center",
          gap: 10,
          marginBottom: 8,
          padding: "10px 14px",
          borderRadius: 12,
          background: "transparent",
          borderLeft: "2px solid rgba(59,130,246,0.15)",
          textDecoration: "none",
          color: "inherit",
        }}
      >
        <span style={{ fontSize: 18, flexShrink: 0 }}>🪞</span>
        <div style={{ flex: 1 }}>
          <div
            style={{
              fontSize: 11,
              fontWeight: 700,
              color: "#1a1a2e",
              marginBottom: 2,
            }}
          >
            Presence
          </div>
          <div style={{ fontSize: 10, color: "#8888a0", lineHeight: 1.4 }}>
            {identityLive.presence?.insight ??
              "データから自動で作成中..."}
          </div>
        </div>
        <div
          style={{
            fontSize: 8,
            color: "#3B82F6",
            fontFamily: mono,
            padding: "3px 6px",
            borderRadius: 6,
            background: "rgba(59,130,246,0.06)",
          }}
        >
          自動生成
        </div>
      </Link>

      {/* Style */}
      <Link
        href="/my-style?source=aneurasync&mode=sync"
        style={{
          display: "flex",
          alignItems: "center",
          gap: 10,
          marginBottom: 10,
          padding: "10px 14px",
          borderRadius: 12,
          background: "transparent",
          borderLeft: "2px solid rgba(168,85,247,0.15)",
          textDecoration: "none",
          color: "inherit",
        }}
      >
        <span style={{ fontSize: 18, flexShrink: 0 }}>◆</span>
        <div style={{ flex: 1 }}>
          <div
            style={{
              fontSize: 11,
              fontWeight: 700,
              color: "#1a1a2e",
              marginBottom: 2,
            }}
          >
            Style DNA
          </div>
          <div style={{ fontSize: 10, color: "#8888a0", lineHeight: 1.4 }}>
            {identityLive.style?.insight ?? "クイズに答えてスタイルDNAを作ろう"}
          </div>
          {(identityLive.style?.pct ?? 0) > 0 && (
            <div
              style={{
                marginTop: 4,
                height: 3,
                borderRadius: 2,
                background: "#ecedf4",
                overflow: "hidden",
                maxWidth: 120,
              }}
            >
              <div
                style={{
                  height: "100%",
                  width: `${identityLive.style?.pct ?? 0}%`,
                  borderRadius: 2,
                  background:
                    "linear-gradient(90deg, #A855F7, #A855F7aa)",
                  transition: "width 0.8s ease",
                }}
              />
            </div>
          )}
        </div>
        {(identityLive.style?.pct ?? 0) === 0 && (
          <div
            style={{
              fontSize: 9,
              color: "#A855F7",
              fontWeight: 600,
              padding: "3px 8px",
              borderRadius: 6,
              background: "rgba(168,85,247,0.08)",
            }}
          >
            入力 →
          </div>
        )}
      </Link>

      {/* DEEPEN (JourneyMap + Genome completeness) */}
      <div
        style={{
          padding: "18px 18px 16px",
          borderRadius: 20,
          background:
            "linear-gradient(145deg, rgba(139,92,246,0.04) 0%, #ffffff 50%, rgba(99,102,241,0.03) 100%)",
          border: "1.5px solid rgba(139,92,246,0.12)",
          boxShadow: "0 4px 16px rgba(139,92,246,0.06)",
        }}
      >
        {/* DEEPEN header */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            marginBottom: 14,
          }}
        >
          <span
            style={{
              fontSize: 9,
              color: "#b0b0c4",
              letterSpacing: 3,
              fontFamily: mono,
            }}
          >
            DEEPEN
          </span>
          <span style={{ fontSize: 10, color: "#8888a0" }}>
            自分を知る旅の地図
          </span>
        </div>

        {/* Journey Map */}
        <div data-tour="journey-map">
          <JourneyMap {...journeyMapProps} />
        </div>

        {/* Genome Card completeness */}
        <div
          style={{
            marginTop: 14,
            paddingTop: 12,
            borderTop: "1px solid rgba(139,92,246,0.08)",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 6,
            }}
          >
            <span style={{ fontSize: 11, fontWeight: 700, color: "#1a1a2e" }}>
              Genome Card 完成度
            </span>
            <span
              style={{
                fontSize: 12,
                fontWeight: 800,
                color: "#8B5CF6",
                fontFamily: mono,
              }}
            >
              {genomeCompleteness}%
            </span>
          </div>
          <div
            style={{
              height: 6,
              borderRadius: 3,
              background: "#ecedf4",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                height: "100%",
                width: `${genomeCompleteness}%`,
                borderRadius: 3,
                background:
                  "linear-gradient(90deg, #8B5CF6, #6366F1)",
                transition: "width 1s ease",
                boxShadow: "0 0 8px rgba(139,92,246,0.3)",
              }}
            />
          </div>
          <div
            style={{
              fontSize: 10,
              color: "#8888a0",
              marginTop: 6,
              lineHeight: 1.5,
            }}
          >
            完成度が上がるほど、Rendezvousでもっといい出会いが見つかるよ
          </div>

          {/* ── Guided Waypoint (控えめ脇役) ── */}
          <div style={{ marginTop: 8, paddingTop: 8, borderTop: "1px solid rgba(0,0,0,0.04)", opacity: 0.85 }}>
            <div style={{ fontSize: 8, color: "#b0b0c4", letterSpacing: 1.5, fontFamily: mono, marginBottom: 6 }}>
              NEXT STEPS
            </div>
            {(() => {
              const steps = identityElements
                .filter(e => !e.isAutoGenerated)
                .sort((a, b) => (b.pct > 0 ? 1 : 0) - (a.pct > 0 ? 1 : 0))
                .slice(0, 3)
                .map(e => ({
                  label: e.label,
                  pct: e.pct,
                  href: e.href,
                  done: e.pct >= 20,
                  emoji: e.emoji,
                }));
              const currentIdx = steps.findIndex(s => !s.done);
              return (
                <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  {steps.map((s, i) => {
                    const isCurrent = i === currentIdx;
                    return (
                      <Link
                        key={s.label}
                        href={s.href}
                        style={{
                          display: "flex", alignItems: "center", gap: 8,
                          padding: "6px 10px", borderRadius: 10,
                          background: isCurrent ? "rgba(99,102,241,0.06)" : "transparent",
                          border: isCurrent ? "1px solid rgba(99,102,241,0.15)" : "1px solid transparent",
                          textDecoration: "none", color: "inherit",
                          transition: "all 0.2s",
                        }}
                      >
                        <span style={{
                          fontSize: 11, width: 20, textAlign: "center",
                          color: s.done ? "#22c55e" : isCurrent ? "#6366F1" : "#c8c8dc",
                          fontWeight: 700,
                        }}>
                          {s.done ? "✓" : isCurrent ? "📍" : "○"}
                        </span>
                        <span style={{
                          fontSize: 11, fontWeight: isCurrent ? 700 : 500,
                          color: s.done ? "#8888a0" : "#1a1a2e",
                        }}>
                          {s.emoji} {s.label}
                        </span>
                        {isCurrent && (
                          <span style={{
                            marginLeft: "auto", fontSize: 10, color: "#6366F1", fontWeight: 600,
                          }}>
                            始める →
                          </span>
                        )}
                        {s.done && (
                          <span style={{
                            marginLeft: "auto", fontSize: 10, color: "#22c55e",
                            fontFamily: mono,
                          }}>
                            {s.pct}%
                          </span>
                        )}
                      </Link>
                    );
                  })}
                </div>
              );
            })()}
          </div>
        </div>
      </div>
    </section>
  );
}
