// app/(culcept)/calendar/_lib/travel/locationNotesData.ts
// Location Notes（ロケーションノート）京都府サンプルデータ — Concept 8/12〜18 準拠。
// trip(旅行プラン) / spot(単体スポット) を 王道(classic) / 穴場(hidden)、地元民(local) / 旅行者(traveler) で分類。
// 写真は全て placeholder（実写真でない印「サンプル」付き・捏造しない・honesty）。UIロジックは持たない純データ。

import type {
  LocationNotesData,
  LocationItem,
  TravelTheme,
  TravelPhoto,
  PhotoTone,
} from "./types";

/** placeholder 写真ヘルパ（abstract タイル＋地名ラベル）。 */
function ph(label: string, tone: PhotoTone): TravelPhoto {
  return { source: "placeholder", label, tone };
}

// ---------------------------------------------------------------------------
// テーマ（Concept 17「すべてのテーマ」）
// ---------------------------------------------------------------------------
const THEMES: TravelTheme[] = [
  { key: "quiet-morning", label: "静かな朝", description: "人の少ない朝の時間に、心が整う旅を。澄んだ空気とやさしい光に包まれて。", photo: ph("静かな朝", "garden") },
  { key: "photogenic", label: "写真映え", description: "切り取りたくなる風景を、めぐる一日。", photo: ph("写真映え", "sunset") },
  { key: "solo", label: "一人旅", description: "自分のペースで、静かに歩く京都。", photo: ph("一人旅", "street") },
  { key: "food-walk", label: "食べ歩き", description: "京の味を、少しずつ味わいながら。", photo: ph("食べ歩き", "food") },
  { key: "morning-walk", label: "朝の散歩", description: "目覚めたばかりの街を、ゆっくりと。", photo: ph("朝の散歩", "street") },
  { key: "night-view", label: "夜景", description: "灯りに照らされる、もう一つの京都。", photo: ph("夜景", "sunset") },
  { key: "healing", label: "癒し", description: "緑と水のそばで、深く息を吸う。", photo: ph("癒し", "garden") },
  { key: "family", label: "家族旅行", description: "子どもも大人も、笑顔になれる一日。", photo: ph("家族旅行", "neutral") },
  { key: "temples", label: "寺社めぐり", description: "千年の祈りに、静かに触れる。", photo: ph("寺社めぐり", "temple") },
  { key: "matcha", label: "抹茶", description: "一服の抹茶に、京都の時間を感じる。", photo: ph("抹茶", "garden") },
];

// ---------------------------------------------------------------------------
// 旅行プラン（trip）
// ---------------------------------------------------------------------------
const TRIPS: LocationItem[] = [
  {
    id: "t-gion-quiet",
    kind: "trip",
    prefecture: "京都府",
    title: "祇園と東山をめぐる、静かな京都の一日",
    areaLabel: "京都市・祇園〜東山エリア",
    classification: "standard",
    source: "traveler",
    author: { name: "Traveler 由香", source: "traveler", roleLabel: "3回目の京都" },
    genre: "寺社・文化",
    themeKeys: ["quiet-morning", "temples", "solo"],
    tags: ["静かさ", "朝が気持ちいい", "歩きやすい"],
    rating: 4.8,
    ratingCount: 1280,
    description: "都市の喧騒を離れ、朝の祇園と東山を静かに歩く。歴史と文化に触れながら、しばらく季節を感じる一日。",
    photo: ph("祇園・八坂の塔", "sunset"),
    durationLabel: "日帰り",
    spotCount: 5,
    stops: ["八坂の塔", "二寧坂", "高台寺", "石塀小路", "花見小路"],
    matchPct: 96,
    matchReasons: ["静かさ重視のあなたに", "朝の時間を活かす構成", "歩いて回れる距離感"],
  },
  {
    id: "t-classic-1day",
    kind: "trip",
    prefecture: "京都府",
    title: "八坂の塔・清水寺・祇園・伏見稲荷 王道1日ルート",
    areaLabel: "京都市・東山〜伏見エリア",
    classification: "classic",
    source: "traveler",
    author: { name: "Kyoto Local M", source: "local", roleLabel: "京都在住8年" },
    genre: "寺社・文化",
    themeKeys: ["temples", "photogenic"],
    tags: ["定番", "はじめての京都", "外せない"],
    rating: 4.8,
    ratingCount: 2240,
    description: "京都を代表する名所を一日で巡る、定番の王道ルート。歴史・景観・文化をまとめて満喫できる一日。",
    photo: ph("清水寺", "temple"),
    durationLabel: "日帰り",
    spotCount: 4,
    stops: ["八坂の塔", "清水寺", "祇園", "伏見稲荷大社"],
    matchPct: 88,
    matchReasons: ["はじめての京都に最適", "写真映えスポット多数"],
  },
  {
    id: "t-arashiyama-hidden",
    kind: "trip",
    prefecture: "京都府",
    title: "嵐山の自然と、隠れ家ランチの半日",
    areaLabel: "京都市・嵐山〜嵯峨エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local 健", source: "local", roleLabel: "嵯峨育ち" },
    genre: "自然・散策",
    themeKeys: ["healing", "quiet-morning"],
    tags: ["静か", "地元の味", "竹林の奥"],
    rating: 4.7,
    ratingCount: 612,
    description: "観光客の流れから少し外れた嵐山の小径と、地元で愛される隠れ家のランチをめぐる半日。",
    photo: ph("嵐山・竹林", "garden"),
    durationLabel: "半日",
    spotCount: 3,
    stops: ["竹林の小径（奥）", "隠れ家ランチ", "大河内山荘"],
  },
  {
    id: "t-fushimi-dawn",
    kind: "trip",
    prefecture: "京都府",
    title: "伏見稲荷 早朝の千本鳥居コース",
    areaLabel: "京都市・伏見エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local J", source: "local", roleLabel: "伏見在住" },
    genre: "寺社・文化",
    themeKeys: ["quiet-morning", "photogenic", "temples"],
    tags: ["早朝", "人が少ない", "静寂"],
    rating: 4.9,
    ratingCount: 540,
    description: "人で混み合う前の早朝に、千本鳥居を静かに歩く。朝霧と朱色の鳥居が幻想的な、特別な時間。",
    photo: ph("千本鳥居", "sunset"),
    durationLabel: "半日",
    spotCount: 2,
    stops: ["伏見稲荷大社", "稲荷山 奥社"],
    matchPct: 91,
    matchReasons: ["静かさ重視のあなたに", "早朝の光が美しい"],
  },
  {
    id: "t-three-heritage",
    kind: "trip",
    prefecture: "京都府",
    title: "京都三大世界遺産 1日コース",
    areaLabel: "京都市・洛西〜洛北エリア",
    classification: "classic",
    source: "traveler",
    author: { name: "Traveler 拓也", source: "traveler", roleLabel: "歴史好き" },
    genre: "寺社・文化",
    themeKeys: ["temples", "photogenic"],
    tags: ["世界遺産", "定番", "見ごたえ"],
    rating: 4.7,
    ratingCount: 1020,
    description: "金閣寺・龍安寺・仁和寺を効率よくめぐる、世界遺産づくしの一日。",
    photo: ph("金閣寺", "temple"),
    durationLabel: "日帰り",
    spotCount: 3,
    stops: ["金閣寺", "龍安寺", "仁和寺"],
  },
  {
    id: "t-kiyomizu-night",
    kind: "trip",
    prefecture: "京都府",
    title: "清水寺と祇園、夜さんぽコース",
    areaLabel: "京都市・東山エリア",
    classification: "classic",
    source: "traveler",
    author: { name: "Traveler 美咲", source: "traveler", roleLabel: "2回目の京都" },
    genre: "寺社・文化",
    themeKeys: ["night-view", "photogenic"],
    tags: ["夜景", "ライトアップ", "ロマンチック"],
    rating: 4.6,
    ratingCount: 880,
    description: "灯りに照らされた清水寺と石畳の坂を、夜にゆっくり歩く。昼とは違う京都の表情。",
    photo: ph("清水寺 夜", "sunset"),
    durationLabel: "夜",
    spotCount: 3,
    stops: ["清水寺", "二寧坂", "祇園"],
  },
  {
    id: "t-moss-zen",
    kind: "trip",
    prefecture: "京都府",
    title: "朝の苔寺と禅、静寂コース",
    areaLabel: "京都市・洛西エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local 蓮", source: "local", roleLabel: "茶道を嗜む" },
    genre: "寺社・文化",
    themeKeys: ["quiet-morning", "healing", "temples"],
    tags: ["静寂", "苔", "予約制"],
    rating: 4.8,
    ratingCount: 320,
    description: "予約制の苔寺で写経と庭の静けさに触れ、禅の時間を過ごす。喧騒から最も遠い京都。",
    photo: ph("苔寺の庭", "garden"),
    durationLabel: "半日",
    spotCount: 2,
    stops: ["西芳寺（苔寺）", "鈴虫寺"],
  },
  {
    id: "t-cafe-free",
    kind: "trip",
    prefecture: "京都府",
    title: "京都カフェめぐり、自由コース",
    areaLabel: "京都市・中心部",
    classification: "standard",
    source: "traveler",
    author: { name: "Traveler さおり", source: "traveler", roleLabel: "カフェ巡りが趣味" },
    genre: "カフェ・グルメ",
    themeKeys: ["food-walk", "solo"],
    tags: ["カフェ", "町家", "自分のペース"],
    rating: 4.5,
    ratingCount: 760,
    description: "町家を改装した名店から話題の新店まで、気の向くままにカフェをめぐる自由な一日。",
    photo: ph("町家カフェ", "food"),
    durationLabel: "日帰り",
    spotCount: 4,
    stops: ["% ARABICA", "茶寮 宝泉", "然カフェ", "錦市場"],
  },
  {
    id: "t-2night-stay",
    kind: "trip",
    prefecture: "京都府",
    title: "2泊3日で愉しむ、王道京都ステイ",
    areaLabel: "京都市・全域",
    classification: "classic",
    source: "traveler",
    author: { name: "Traveler 健一", source: "traveler", roleLabel: "家族旅行" },
    genre: "総合",
    themeKeys: ["temples", "family", "food-walk"],
    tags: ["2泊3日", "王道", "家族向け"],
    rating: 4.7,
    ratingCount: 1340,
    description: "東山・嵐山・伏見をバランスよく巡る、はじめての京都にちょうどいい2泊3日。",
    photo: ph("京都ステイ", "stay"),
    durationLabel: "2泊3日",
    spotCount: 9,
    stops: ["清水寺", "嵐山", "伏見稲荷", "金閣寺", "錦市場"],
    matchPct: 84,
    matchReasons: ["王道を効率よく", "宿泊込みの安心構成"],
  },
  {
    id: "t-ohara-day",
    kind: "trip",
    prefecture: "京都府",
    title: "大原の里、ひなびた一日",
    areaLabel: "京都市・洛北 大原エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local 千鶴", source: "local", roleLabel: "大原在住" },
    genre: "自然・散策",
    themeKeys: ["healing", "quiet-morning"],
    tags: ["里山", "静か", "紅葉前"],
    rating: 4.8,
    ratingCount: 280,
    description: "三千院と勝林院をめぐり、里山の畦道をのんびり歩く。観光地化されきっていない大原の素顔。",
    photo: ph("大原の里", "garden"),
    durationLabel: "日帰り",
    spotCount: 3,
    stops: ["三千院", "勝林院", "宝泉院"],
  },
];

// ---------------------------------------------------------------------------
// スポット（spot）
// ---------------------------------------------------------------------------
const SPOTS: LocationItem[] = [
  {
    id: "s-ishibe",
    kind: "spot",
    prefecture: "京都府",
    title: "石塀小路の朝さんぽ",
    areaLabel: "祇園・東山エリア",
    classification: "standard",
    source: "local",
    author: { name: "Kyoto Local M", source: "local", roleLabel: "京都在住8年" },
    genre: "散策・路地",
    themeKeys: ["morning-walk", "quiet-morning", "photogenic"],
    tags: ["石畳", "朝が静か", "町家"],
    rating: 4.6,
    ratingCount: 420,
    description: "石塀小路は朝の光が差し込む頃が最も美しく、静かに祇園に佇んでいます。早朝の散歩に最適。",
    photo: ph("石塀小路", "street"),
    hours: "6:00–9:00",
    address: "京都市東山区下河原町",
    matchPct: 93,
    matchReasons: ["朝の静かさが好きなあなたに", "写真映えする路地"],
  },
  {
    id: "s-machiya-cafe",
    kind: "spot",
    prefecture: "京都府",
    title: "静かな町家カフェ 然",
    areaLabel: "東山・八坂エリア",
    classification: "standard",
    source: "local",
    author: { name: "Kyoto Local 彩", source: "local", roleLabel: "近所に住む" },
    genre: "カフェ",
    themeKeys: ["solo", "healing"],
    tags: ["町家", "コーヒー", "ひとり時間"],
    rating: 4.7,
    ratingCount: 310,
    description: "築100年の町家を改装した、地元の人がそっと通う静かなカフェ。中庭を眺める席が特等席。",
    photo: ph("町家カフェ 然", "food"),
    hours: "9:00–18:00",
    address: "京都市東山区",
    priceLevel: "¥¥",
  },
  {
    id: "s-housen",
    kind: "spot",
    prefecture: "京都府",
    title: "茶寮 宝泉",
    areaLabel: "下鴨エリア",
    classification: "standard",
    source: "local",
    author: { name: "Kyoto Local 美保", source: "local", roleLabel: "甘味好き" },
    genre: "和スイーツ・抹茶",
    themeKeys: ["matcha", "healing"],
    tags: ["わらび餅", "庭", "抹茶"],
    rating: 4.8,
    ratingCount: 690,
    description: "美しい庭を眺めながら、注文を受けてから作るわらび餅をいただける名店。静かな贅沢。",
    photo: ph("茶寮 宝泉", "garden"),
    hours: "10:00–17:00",
    address: "京都市左京区下鴨",
    priceLevel: "¥¥",
  },
  {
    id: "s-kamogawa",
    kind: "spot",
    prefecture: "京都府",
    title: "鴨川デルタの夕景",
    areaLabel: "出町柳エリア",
    classification: "standard",
    source: "local",
    author: { name: "Kyoto Local 涼", source: "local", roleLabel: "学生時代から通う" },
    genre: "自然・景観",
    themeKeys: ["photogenic", "healing"],
    tags: ["夕景", "川辺", "のんびり"],
    rating: 4.5,
    ratingCount: 530,
    description: "鴨川が二手に分かれるデルタ地帯。飛び石を渡り、夕暮れの川辺で京都の日常に溶け込む。",
    photo: ph("鴨川デルタ", "sunset"),
    hours: "終日",
    address: "京都市左京区 出町柳",
  },
  {
    id: "s-yasaka-tower",
    kind: "spot",
    prefecture: "京都府",
    title: "八坂の塔と石畳",
    areaLabel: "東山エリア",
    classification: "classic",
    source: "local",
    author: { name: "Kyoto Local M", source: "local", roleLabel: "京都在住8年" },
    genre: "寺社・景観",
    themeKeys: ["photogenic", "temples"],
    tags: ["定番", "写真映え", "石畳"],
    rating: 4.7,
    ratingCount: 1530,
    description: "京都を象徴する五重塔。石畳の坂道から見上げる構図は、誰もが一度は撮りたくなる定番。",
    photo: ph("八坂の塔", "temple"),
    hours: "終日（拝観 10:00–16:00）",
    address: "京都市東山区",
  },
  {
    id: "s-ninenzaka",
    kind: "spot",
    prefecture: "京都府",
    title: "二寧坂の朝",
    areaLabel: "東山エリア",
    classification: "standard",
    source: "local",
    author: { name: "Kyoto Local 直", source: "local", roleLabel: "東山勤務" },
    genre: "散策・路地",
    themeKeys: ["morning-walk", "photogenic"],
    tags: ["石段", "朝が空く", "風情"],
    rating: 4.6,
    ratingCount: 740,
    description: "日中は混み合う二寧坂も、開店前の朝は驚くほど静か。京情緒を独り占めできる時間帯。",
    photo: ph("二寧坂", "street"),
    hours: "早朝がおすすめ",
    address: "京都市東山区",
  },
  {
    id: "s-randen",
    kind: "spot",
    prefecture: "京都府",
    title: "嵐電 嵯峨駅のレトロ",
    areaLabel: "嵐山・嵯峨エリア",
    classification: "standard",
    source: "traveler",
    author: { name: "Traveler 翔", source: "traveler", roleLabel: "鉄道好き" },
    genre: "景観・乗り物",
    themeKeys: ["photogenic", "solo"],
    tags: ["レトロ", "路面電車", "嵐山"],
    rating: 4.4,
    ratingCount: 290,
    description: "嵐山へ向かうレトロな路面電車・嵐電。駅舎や車窓の風景は旅情をかきたてる。",
    photo: ph("嵐電 嵯峨駅", "street"),
    hours: "始発–終電",
    address: "京都市右京区 嵯峨",
  },
  {
    id: "s-arabica",
    kind: "spot",
    prefecture: "京都府",
    title: "% ARABICA 京都 東山",
    areaLabel: "東山・八坂エリア",
    classification: "standard",
    source: "traveler",
    author: { name: "Traveler Mina", source: "traveler", roleLabel: "コーヒー好き" },
    genre: "カフェ",
    themeKeys: ["food-walk", "photogenic"],
    tags: ["コーヒー", "行列", "ラテアート"],
    rating: 4.5,
    ratingCount: 2100,
    description: "八坂の塔を望む人気のコーヒースタンド。シンプルで洗練された一杯を片手に東山さんぽ。",
    photo: ph("% ARABICA", "food"),
    hours: "8:00–18:00",
    address: "京都市東山区",
    priceLevel: "¥¥",
  },
  {
    id: "s-fushimi",
    kind: "spot",
    prefecture: "京都府",
    title: "伏見稲荷大社",
    areaLabel: "伏見エリア",
    classification: "classic",
    source: "traveler",
    author: { name: "Traveler 大輔", source: "traveler", roleLabel: "海外からの友人と" },
    genre: "寺社・文化",
    themeKeys: ["temples", "photogenic"],
    tags: ["千本鳥居", "定番", "24時間"],
    rating: 4.8,
    ratingCount: 4200,
    description: "朱色の千本鳥居が連なる、京都随一の人気スポット。早朝か夜は比較的ゆっくり歩ける。",
    photo: ph("伏見稲荷", "sunset"),
    hours: "24時間（授与所 7:00–18:00）",
    address: "京都市伏見区",
  },
  {
    id: "s-kiyomizu",
    kind: "spot",
    prefecture: "京都府",
    title: "清水寺",
    areaLabel: "東山エリア",
    classification: "classic",
    source: "traveler",
    author: { name: "Traveler 結衣", source: "traveler", roleLabel: "修学旅行ぶり" },
    genre: "寺社・文化",
    themeKeys: ["temples", "photogenic"],
    tags: ["世界遺産", "舞台", "定番"],
    rating: 4.8,
    ratingCount: 5300,
    description: "「清水の舞台」で名高い世界遺産。舞台から望む京都市街の眺めは圧巻。",
    photo: ph("清水寺", "temple"),
    hours: "6:00–18:00",
    address: "京都市東山区",
  },
  {
    id: "s-hanamikoji",
    kind: "spot",
    prefecture: "京都府",
    title: "祇園 花見小路",
    areaLabel: "祇園エリア",
    classification: "classic",
    source: "traveler",
    author: { name: "Traveler 彩花", source: "traveler", roleLabel: "和の風情を求めて" },
    genre: "散策・花街",
    themeKeys: ["photogenic", "night-view"],
    tags: ["花街", "石畳", "夕暮れ"],
    rating: 4.5,
    ratingCount: 1880,
    description: "茶屋が軒を連ねる祇園のメインストリート。夕暮れ時の灯りが京都らしい風情を醸す。",
    photo: ph("花見小路", "street"),
    hours: "夕方–夜がおすすめ",
    address: "京都市東山区 祇園",
  },
  {
    id: "s-shorin-in",
    kind: "spot",
    prefecture: "京都府",
    title: "大原・勝林院の参道",
    areaLabel: "洛北 大原エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local J", source: "local", roleLabel: "大原に通って20年" },
    genre: "寺社・自然",
    themeKeys: ["quiet-morning", "healing", "temples"],
    tags: ["静寂", "里山", "声明発祥"],
    rating: 4.9,
    ratingCount: 180,
    description: "誰も知らない、静寂の神社。大原の奥にひっそりと佇む勝林院の参道は、訪れる人もまばら。",
    photo: ph("勝林院の参道", "garden"),
    hours: "9:00–17:00",
    address: "京都市左京区 大原",
    whySpecial: "声明（仏教音楽）発祥の地で、堂内に身を置くと音の余韻が驚くほど長く響きます。",
    whyHidden: "アクセスが不便で、案内も少なく、訪れる人がほとんどいないため。",
    matchPct: 89,
    matchReasons: ["静けさを求めるあなたに", "人混みを避けたい旅に"],
  },
  {
    id: "s-philosophy",
    kind: "spot",
    prefecture: "京都府",
    title: "哲学の道 早朝",
    areaLabel: "洛東 銀閣寺エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local 史", source: "local", roleLabel: "散歩が日課" },
    genre: "自然・散策",
    themeKeys: ["quiet-morning", "morning-walk", "healing"],
    tags: ["早朝", "水路", "静か"],
    rating: 4.6,
    ratingCount: 240,
    description: "観光客が訪れる前の早朝、せせらぎだけが響く哲学の道。思索にふけるのにふさわしい静けさ。",
    photo: ph("哲学の道", "garden"),
    hours: "早朝がおすすめ",
    address: "京都市左京区",
    whySpecial: "朝もやの中の水路沿いは、昼間とはまるで別の場所のような静謐さ。",
    whyHidden: "美しさは早朝限定で、その時間に歩く人がほとんどいないため。",
  },
  {
    id: "s-shisendo",
    kind: "spot",
    prefecture: "京都府",
    title: "詩仙堂の庭",
    areaLabel: "洛北 一乗寺エリア",
    classification: "hidden",
    source: "traveler",
    author: { name: "Traveler 倫子", source: "traveler", roleLabel: "庭園めぐりが好き" },
    genre: "寺社・庭園",
    themeKeys: ["healing", "quiet-morning"],
    tags: ["庭園", "ししおどし", "静寂"],
    rating: 4.7,
    ratingCount: 360,
    description: "ししおどしの音が響く、白砂と緑の名庭。縁側に座ると時間を忘れる、知る人ぞ知る庭。",
    photo: ph("詩仙堂", "garden"),
    hours: "9:00–17:00",
    address: "京都市左京区 一乗寺",
    whySpecial: "縁側から眺める庭の構図が完璧で、長く座っていたくなる稀有な空間。",
    whyHidden: "中心部から離れた一乗寺にあり、大型観光ルートから外れているため。",
  },
  {
    id: "s-enkoji",
    kind: "spot",
    prefecture: "京都府",
    title: "圓光寺 紅葉前の青もみじ",
    areaLabel: "洛北 一乗寺エリア",
    classification: "hidden",
    source: "local",
    author: { name: "Kyoto Local 楓", source: "local", roleLabel: "写真が趣味" },
    genre: "寺社・庭園",
    themeKeys: ["healing", "photogenic"],
    tags: ["青もみじ", "水鏡", "紅葉前"],
    rating: 4.8,
    ratingCount: 210,
    description: "紅葉の名所として知られるが、人の少ない紅葉前の青もみじと水鏡が、実は最も美しい。",
    photo: ph("圓光寺 青もみじ", "garden"),
    hours: "9:00–17:00",
    address: "京都市左京区 一乗寺",
    whySpecial: "床や水面に映り込む新緑のリフレクションが息をのむ美しさ。",
    whyHidden: "皆が紅葉の時期に集中するため、それ以外の季節はほぼ貸し切り状態。",
  },
];

// ---------------------------------------------------------------------------
// 束ねたデータ
// ---------------------------------------------------------------------------
export const KYOTO_LOCATION_NOTES: LocationNotesData = {
  prefectures: ["京都府", "大阪府", "東京都", "奈良県", "石川県", "北海道", "沖縄県"],
  defaultPrefecture: "京都府",
  preferenceChips: [
    { label: "学び", active: true },
    { label: "静かさ重視", active: true },
    { label: "関西圏", active: true },
    { label: "写真映え" },
    { label: "食" },
  ],
  matchReasons: [
    "あなたが過去に「静かな朝」「寺社めぐり」を多く選んでいるため、人混みを避けた早朝の構成を優先しています。",
    "歩いて回れる距離感の旅程を好む傾向から、移動の少ないコンパクトなプランを上位に。",
    "関西圏での滞在が多く、王道だけでなく地元民の穴場も取り混ぜています。",
  ],
  infoSources: [
    { label: "検索", channel: "Google", note: "定番の下調べに" },
    { label: "SNS", channel: "Instagram", note: "写真映えの発見に" },
    { label: "地元民の口コミ", channel: "Local", note: "穴場はここから" },
    { label: "旅行者レビュー", channel: "Review", note: "実際の声を確認" },
    { label: "旅行誌", channel: "Magazine", note: "特集で深掘り" },
  ],
  areaChips: [
    { label: "祇園", reading: "ぎおん", count: 12 },
    { label: "嵐山", reading: "あらしやま", count: 9 },
    { label: "左京区", reading: "さきょうく", count: 14 },
    { label: "伏見", reading: "ふしみ", count: 7 },
    { label: "北山", reading: "きたやま", count: 5 },
    { label: "東山", reading: "ひがしやま", count: 16 },
  ],
  hiddenHints: ["早朝", "静寂", "平日", "少人数", "雨の日", "紅葉前", "小さな店", "季節限定"],
  themes: THEMES,
  items: [...TRIPS, ...SPOTS],
};

/** 都道府県でデータを絞り込む（都道府県セレクタ反映用）。 */
export function getLocationNotes(prefecture: string): LocationNotesData {
  return {
    ...KYOTO_LOCATION_NOTES,
    items: KYOTO_LOCATION_NOTES.items.filter((it) => it.prefecture === prefecture),
  };
}
